# Generated by Django 4.2.6 on 2023-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Short', 'Short Course'), ('Long', 'Long Course')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
